In [1]:
# libraries
from scipy.io import loadmat
from pathlib import Path

In [2]:
# load database
mat = loadmat('../db.mat')
labels = mat['issecure']
VM = mat['VM']
VA = mat['VA']
# Reshape sload half of the data is active power, the other one is reactive power
SLOAD = mat['SLOAD']

In [12]:
samples, powers = SLOAD.shape
PQLOAD = SLOAD.reshape((samples, powers//2, 2))

In [16]:
PQLOAD[:,:,0]

array([[ 351.27429879,  198.36611944,    7.49373368,  362.52210247,
         695.31814543,  236.11516557,  205.36957957,  301.34396188,
         246.66582784, 1266.70587719,  199.81856172,  193.80910065,
         146.71164336,   29.12411137,  108.60631687,  -85.32116909,
          17.31002347,   25.17813884,    4.6297418 ],
       [ 371.11378662,  251.61262284,    8.089928  ,  370.35041945,
         757.75811685,  287.33581132,  256.88469581,  359.13209676,
         342.67937449, 1385.71889464,  218.87176464,  195.91293453,
         182.90608711,   36.35532703,  128.66613445,  -87.7870971 ,
          19.21796064,   29.72866737,    4.91155511],
       [ 248.64500047,  173.42283995,    4.86937336,  247.20692473,
         484.2880476 ,  153.80693974,  161.426487  ,  195.6530022 ,
         194.08444937,  756.32668705,  125.22284839,  115.06488051,
         113.41332137,   21.43465295,   79.59396705,  -69.00677023,
          10.80148986,   19.7258263 ,    3.16282316],
       [ 377.66377776,

In [11]:
SLOAD

array([[ 3.51274299e+02,  5.10475203e+02,  1.98366119e+02,
         5.55867711e+02,  7.49373368e+00,  3.05259679e+02,
         3.62522102e+02,  1.62589583e+02,  6.95318145e+02,
         2.66655336e+02,  2.36115166e+02,  3.02102349e+02,
         2.05369580e+02,  1.32580981e+02,  3.01343962e+02,
         1.69497435e+02,  2.46665828e+02,  9.02546392e+00,
         1.26670588e+03,  2.25924339e+00,  1.99818562e+02,
         9.31515853e+01,  1.93809101e+02,  7.53560735e+01,
         1.46711643e+02,  3.06825214e+01,  2.91241114e+01,
         1.03077038e+02,  1.08606317e+02,  9.84248085e+01,
        -8.53211691e+01,  4.69148278e+01,  1.73100235e+01,
         6.59132978e+01,  2.51781388e+01,  2.82959169e+01,
         4.62974180e+00,  2.53539209e+02],
       [ 3.71113787e+02,  5.88928014e+02,  2.51612623e+02,
         5.21760954e+02,  8.08992800e+00,  3.18930388e+02,
         3.70350419e+02,  1.78895763e+02,  7.57758117e+02,
         2.75781686e+02,  2.87335811e+02,  3.17039128e+02,
         2.56

In [6]:
labels

array([[1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1]],
      dtype=uint8)